/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 employee.gltf 
Author: rosaliarenda (https://sketchfab.com/rosaliarenda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ipazia-avatar-catwalk-idle-twist-r-eea224822e4847f0996a14596466a762
Title: Ipazia-avatar@ Catwalk Idle Twist R
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Employee(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/employee.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="ac94a78a70cc41468901fe9bba775c53fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_89" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_91" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_93" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_95" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_97" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_99" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_101" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_103" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_105" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.Object_90.skeleton} />
                    <skinnedMesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.Object_92.skeleton} />
                    <skinnedMesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Object_94.skeleton} />
                    <skinnedMesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Object_96.skeleton} />
                    <skinnedMesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Object_98.skeleton} />
                    <skinnedMesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Object_100.skeleton} />
                    <skinnedMesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Object_102.skeleton} />
                    <skinnedMesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Object_104.skeleton} />
                    <skinnedMesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Object_106.skeleton} />
                  </group>
                </group>
                <group name="EyeLeft" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="EyeRight" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Wolf3D_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Wolf3D_Teeth" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Wolf3D_Hair" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Wolf3D_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Wolf3D_Outfit_Bottom" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Wolf3D_Outfit_Footwear" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Wolf3D_Outfit_Top" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/employee.gltf')
